import type { MockFuelDispatch, MockInterSBUTransfer, MockFuelTank } from './types';

export const MOCK_FUEL_DISPATCHES: MockFuelDispatch[] = [
  {
    id: 'FD-2026-0001',
    type: 'fuel_dispatch',
    assetTag: 'CR-001',
    assetType: 'crane',
    siteId: 'site-a',
    siteName: 'Site A — Hulhumalé',
    fuelType: 'diesel',
    requestedLiters: 200,
    dispensedLiters: 200,
    status: 'dispensed',
    requestedBy: 'user-sm',
    approvedBy: 'user-gm',
    dispatchedBy: 'user-proc',
    createdAt: '2026-05-28T06:00:00Z',
    completedAt: '2026-05-28T08:30:00Z',
    cost: 320,
  },
  {
    id: 'FD-2026-0002',
    type: 'fuel_dispatch',
    assetTag: 'EX-001',
    assetType: 'excavator',
    siteId: 'site-a',
    siteName: 'Site A — Hulhumalé',
    fuelType: 'diesel',
    requestedLiters: 350,
    dispensedLiters: 350,
    status: 'dispensed',
    requestedBy: 'user-sm',
    approvedBy: 'user-gm',
    dispatchedBy: 'user-proc',
    createdAt: '2026-05-28T07:00:00Z',
    completedAt: '2026-05-28T09:00:00Z',
    cost: 560,
  },
  {
    id: 'FD-2026-0003',
    type: 'fuel_dispatch',
    assetTag: 'GN-002',
    assetType: 'generator',
    siteId: 'site-b',
    siteName: 'Site B — Airport',
    fuelType: 'diesel',
    requestedLiters: 100,
    dispensedLiters: 0,
    status: 'approved',
    requestedBy: 'user-sm',
    approvedBy: 'user-gm',
    createdAt: '2026-05-28T09:00:00Z',
    cost: 160,
    notes: 'Scheduled for afternoon dispatch',
  },
  {
    id: 'FD-2026-0004',
    type: 'fuel_dispatch',
    assetTag: 'DZ-003',
    assetType: 'dozer',
    siteId: 'site-a',
    siteName: 'Site A — Hulhumalé',
    fuelType: 'diesel',
    requestedLiters: 500,
    dispensedLiters: 0,
    status: 'requested',
    requestedBy: 'user-mech',
    createdAt: '2026-05-28T10:15:00Z',
    cost: 800,
  },
  {
    id: 'FD-2026-0005',
    type: 'fuel_dispatch',
    assetTag: 'RC-002',
    assetType: 'roller',
    siteId: 'site-yard',
    siteName: 'Harbor Yard',
    fuelType: 'diesel',
    requestedLiters: 80,
    dispensedLiters: 0,
    status: 'requested',
    requestedBy: 'user-sm',
    createdAt: '2026-05-28T11:00:00Z',
    cost: 128,
  },
  {
    id: 'FD-2026-0006',
    type: 'fuel_dispatch',
    assetTag: 'FL-004',
    assetType: 'forklift',
    siteId: 'site-b',
    siteName: 'Site B — Airport',
    fuelType: 'diesel',
    requestedLiters: 50,
    dispensedLiters: 0,
    status: 'rejected',
    requestedBy: 'user-mech',
    createdAt: '2026-05-27T14:00:00Z',
    cost: 80,
    notes: 'Rejected: Tank levels low, defer to next week',
  },
];

export const MOCK_FUEL_TANKS: MockFuelTank[] = [
  { id: 'tank-a1', name: 'Tank A1 — Diesel', fuelType: 'diesel', capacity: 10000, current: 7200, siteId: 'site-a' },
  { id: 'tank-a2', name: 'Tank A2 — Petrol', fuelType: 'petrol', capacity: 5000, current: 3100, siteId: 'site-a' },
  { id: 'tank-b1', name: 'Tank B1 — Diesel', fuelType: 'diesel', capacity: 8000, current: 1500, siteId: 'site-b' },
  { id: 'tank-yard', name: 'Tank Yard — Diesel', fuelType: 'diesel', capacity: 15000, current: 6800, siteId: 'site-yard' },
];

export const MOCK_INTER_SBU_TRANSFERS: MockInterSBUTransfer[] = [
  {
    id: 'IST-2026-0001',
    fromSBU: 'WLI',
    toSBU: 'EMS',
    assetId: 'EX-001',
    assetName: 'Caterpillar 320D Excavator',
    reason: 'Engine overhaul required — EMS motor workshop',
    status: 'in_transit',
    requestedBy: 'user-gm',
    approvedBy: 'user-super',
    fromSite: 'Site A — Hulhumalé',
    toSite: 'EMS Workshop — Malé',
    createdAt: '2026-05-27T10:00:00Z',
  },
  {
    id: 'IST-2026-0002',
    fromSBU: 'WLI',
    toSBU: 'MPL',
    assetId: 'GN-002',
    assetName: 'Cummins 500KVA Generator',
    reason: 'Preventive maintenance cycle 3',
    status: 'requested',
    requestedBy: 'user-sm',
    fromSite: 'Site B — Airport',
    toSite: 'MPL Depot — Hulhumalé',
    createdAt: '2026-05-28T08:00:00Z',
  },
  {
    id: 'IST-2026-0003',
    fromSBU: 'EMS',
    toSBU: 'WLI',
    assetId: 'CR-001',
    assetName: 'Liebherr LTM 1100 Crane',
    reason: 'Hydraulic system repair completed — returning to service',
    status: 'completed',
    requestedBy: 'user-gm',
    approvedBy: 'user-super',
    fromSite: 'EMS Workshop — Malé',
    toSite: 'Site A — Hulhumalé',
    createdAt: '2026-05-25T12:00:00Z',
    completedAt: '2026-05-28T06:00:00Z',
  },
];

export const MOCK_INTERSBU_TRANSFERS = MOCK_INTER_SBU_TRANSFERS;
